### ISSUE TITLE
video with 2 monitors

### ISSUE THREAD

**Issue by juceliohv** [cheesecakeufo/komorebi#115]
The video dont play in 2 monitor on the same time.

The right click only work in main screen.

**Comment by thedonquixotic** [comment]
@juceliohv please close this issue. There is a fix for this already in the pull requests, but the project maintainer has seemingly abandoned the project. If you are interested I have created a fork which I intend to help maintain. If you'd be interested in contributing check out: https://github.com/thedonquixotic/komorebi

**Comment by juceliohv** [comment]
ok!
