### ISSUE TITLE
How to move clock?

### ISSUE THREAD

**Issue by primeroctubre** [cheesecakeufo/komorebi#150]
The clock is in the center. How to move to the rigth? how do I start to the right of the screen?

**Comment by AkibaIllusionLinux** [comment]
You can do it with wallpaper creator or manually as I will show you.

![deepinscreenshot_select-area_20190208204043](https://user-images.githubusercontent.com/44012887/52513591-27b09d00-2be2-11e9-8fa1-ec25b275a7ca.png)

![deepinscreenshot_select-area_20190208203849](https://user-images.githubusercontent.com/44012887/52513601-38611300-2be2-11e9-8955-8badec30f72b.png)

don't forget to save config settings and refresh background to take effect.

If you have more questions, you are free to ask.

**Comment by primeroctubre** [comment]
Thank you. Where do I find the topics? to be able to edit the config. Thank you so much.

**Comment by primeroctubre** [comment]
Thank you. Where do I find the topics? to be able to edit the config. Thank you so much.

**Comment by AkibaIllusionLinux** [comment]
> Thank you. Where do I find the topics? to be able to edit the config. Thank you so much.

Once installed komorebi he will create a route:

System/Resources/Komorebi 

In this folder path you must paste your content in administrator mode.

**Comment by primeroctubre** [comment]
Thank you. I found it in /usr/share/komorebi /"""wallpaper""". Thank you very much, I can edit the config, I'll see now how to refresh it.

**Comment by primeroctubre** [comment]
Thank you. I found it in /usr/share/komorebi /"""wallpaper""". Thank you very much, I can edit the config,

**Comment by primeroctubre** [comment]
Thank you. I found it in /usr/share/komorebi /"""wallpaper""". Thank you very much, I can edit the config,

**Comment by primeroctubre** [comment]
Thank you. I found it in /usr/share/komorebi /"""wallpaper""". Thank you very much, I can edit the config,

**Comment by AkibaIllusionLinux** [comment]
/usr/share/komorebi / ???    What distro aand komorebi version are you using?

**Comment by primeroctubre** [comment]
Manjaro Linux.

![captura de pantalla de 2019-02-09 15-04-38](https://user-images.githubusercontent.com/45472613/52524488-419ebe00-2c7c-11e9-9dbf-5b47a34a3a2c.png)

**Comment by primeroctubre** [comment]
![deepinscreenshot_20190209200944](https://user-images.githubusercontent.com/45472613/52527794-154f6580-2cad-11e9-9aac-457e7ea4c270.png)

![captura de pantalla de 2019-02-09 20-17-44](https://user-images.githubusercontent.com/45472613/52527796-226c5480-2cad-11e9-88fc-a5aa6e0eb82b.png)
