### ISSUE TITLE
No right click on desktop after unistall komorebi

### ISSUE THREAD

**Issue by TheFuzzStone** [cheesecakeufo/komorebi#168]
System: **Ubuntu 18.04.2**
DE: **Cinnamon 4.0.9**
Kernel: **4.15.0-50-generic**

---

* Gnome tweak tool didn't help (probably because this is a Cinnamon DE);
* I did a similar operation in the `cinnamon-settings`, didn't helped;

**Comment by lss4** [comment]
What it looked to me is that the program runs its own desktop frame on top of the actual one, and it has its own menu and icon processing logics.

If that's the case, issues #162, #163 (and probably some other issues opened here regarding interactions with icons and original DE functionalities) would be related.

System: Manjaro XFCE
DE: XFCE 4.13
Kernel: 5.1.4-1-MANJARO

**Comment by intervisionlord** [comment]
Same issue for me on debian 10.1 with cinnamon 3.8.8. No right-click reaction at all
