### ISSUE TITLE
No right-click menu when using menu to start komorebi

### ISSUE THREAD

**Issue by mjt33** [cheesecakeufo/komorebi#174]
Odd issue. First, Xubuntu 19.04 is my os. Installed, clicked on menu entry for komorebi, it opened and wallpaper appeared, but no right-click menu. I restarted and komorebi started and right-click menu appeared.

I quit komorebi, then clicked menu entry to restart it and the right-click menu again did not appear. I quit komorebi via task manager and restarted via terminal and right-click menu appeared.

It seems using the menu entry to start komorebi prevents my right-click menu from being used. Since I'd like to be able to run it without using a terminal, this is preventing me from using the app atm.

**Comment by shadyueh** [comment]
In Ubuntu 18.04.2 LTS this occurrs too
