### ISSUE TITLE
Wont start on Ubuntu 19.10

### ISSUE THREAD

**Issue by KiviTK** [cheesecakeufo/komorebi#194]
The program wont run, when launching it hangs for a bit then shuts down.
I've seen some issues whit libgtop dependencies, I did add the symbolic link, still no luck.
Any ideas what might be the problem?

**Comment by yellowPIKACHU** [comment]
Same problem on elementary OS 5.1 Hera

**Comment by KiviTK** [comment]
Okay, fixed it!
It was indeed a problem with libgtop dependency and symbolic linking was the fix, however, the linking command I pasted was out of date.

So here is a hopefully working one for anyone who has this issue (and a guide to how to find the up to date for you)

`sudo ln -s /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11 /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.10`
was the command for me, but that might differ in the future.

The problem is that the expected version of libgtop is not found as we have a higher version.
So you just list all the libgtop things in your `/usr/lib/x86_64-linux-gnu` see the highest version that you have and create a symlink to that by the name of the old shared object, this way it will find that.

This is kinda wack because if there is a major update to libgtop it will break, but it works for now.
