### ISSUE TITLE
Video wallpaper not working

### ISSUE THREAD

**Issue by swarfendor437** [cheesecakeufo/komorebi#216]
I was hoping with the release of version 2 that this issue would have been resolved but it isn't. I follow the copy and paste in terminal after selecting video to display as wallpaper and it doesn't show. I think it needs a rewrite similar to what was used in Netrunner that worked - even that supported gif wallpapers too!

**Comment by haxxus** [comment]
Hello, im using zorin os kernel 5.6.4, static wallpapers and full menu works but not the live video wallpapers, this error appears when selecting a live wallpaper:

[INFO]: loading Gst
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!

**Comment by swarfendor437** [comment]
> Hello, im using zorin os kernel 5.6.4, static wallpapers and full menu works but not the live video wallpapers, this error appears when selecting a live wallpaper:
> 
> [INFO]: loading Gst
> mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
> mesa: for the --global-isel-abort option: may only occur zero or one times!
> mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!

Yes, I get the same experience - I was using FerenOS x64 KDE Plasma 5.18 while testing this.
I orginally tried it on Zorin 12.x (i.e., first iteration of koberemi. The provided animated wallpapers worked but when it came to short video clips which I have uploaded to Vimeo for people to use as moving wallpapers in Zorin, 15 no longer offered that. It's a bit of a memory haze at the moment what with moderating and all!

**Comment by golygus669** [comment]
I wondering if you are placing a snapshot of the video into the same
directory of where the video is located?

**Comment by swarfendor437** [comment]
No - the guide clearly states choose your video clip then on the next page the instruction to copy and paste the terminal command:

Open 'Terminal' then paste the following:
sudo mv /home/swarfendor437/fountains_in_slowmo /System/Resources/Komorebi
Once done, you can change the wallpaper in 'Change Wallpaper'.

So that is not possible friend.

**Comment by golygus669** [comment]
I know but unless there is a clip of snapshot of the video in the same
directory you just get a black screen.

**Comment by swarfendor437** [comment]
I don't get anything - nothing in the wallpaper chooser as it states it would appear as a choice on restart of application.

**Comment by golygus669** [comment]
On the fourth line "Where is the thumbnail located" you must be able to
type in the location of the snapshot of the video which you have created.
Allen E Thomas

tallawong69@gmail.com

**Comment by swarfendor437** [comment]
Sorted! I wish the instructions were clearer about the thumbnail. I used kdenlive to export a frame and created thumb.png - I now have my moving wallpaper - many thanks!
