### ISSUE TITLE
auto strart

### ISSUE THREAD

**Issue by aminvandh** [cheesecakeufo/komorebi#218]
is there option to start it at startup ?

**Comment by Ev1lbl0w** [comment]
This is pretty straightforward, just copy the application `.desktop` file to your `~/.config/autostart`.

This varies distro by distro, so if you want more help, tell me what distro you're currently using, so I can give you more detailed steps.

**Comment by pendragons-code** [comment]
actually there is an option but you got to right click and go to preferences
