### ISSUE TITLE
Not "live"

### ISSUE THREAD

**Issue by CrystalxCode** [cheesecakeufo/komorebi#229]
No GUI shows, it just changes to the default wallpaper. I am running Ubuntu 18.04 LTS

**Comment by Ev1lbl0w** [comment]
There is no "GUI" when it launches; if it's working correctly, you should be able to right-click on the desktop to show a menu, and from there a settings panel.

**Comment by CrystalxCode** [comment]
> There is no "GUI" when it launches; if it's working correctly, you should be able to right-click on the desktop to show a menu, and from there a settings panel.

That also doesnt show anything. It doesnt show anything, all that is there is the default background.

**Comment by Kangie** [comment]
@CrystalxCode What happens if you start komorebi from a terminal?
