### ISSUE TITLE
There is no uninstall rule for makefile

### ISSUE THREAD

**Issue by kyrie-z** [cheesecakeufo/komorebi#232]
When I want to uninstall, but I can’t find uninstall in makefle, can you improve it?
```
~/komorebi/build$ sudo make uninstall
make: *** 没有规则可制作目标“uninstall”。 停止。 
```

**Comment by Ev1lbl0w** [comment]
We have changed the build system on [our fork](https://github.com/Komorebi-Fork/komorebi) to address that problem.

In this version though, you'll have to manually delete the files. Luckily, this version installs on non-standard paths, so it makes things much easier. Remove:

- /System/Resources/Komorebi
- /System/Applications/
- /usr/share/applications/komorebi.desktop
- /usr/share/applications/wallpapercreator.desktop

**Comment by Kangie** [comment]
@kyrie-z As @Ev1lbl0w said, try our fork over [here](https://github.com/Komorebi-Fork/komorebi). That should solve your problem and provide a few quality-of-life fixes at the same time. :)

**Comment by kyrie-z** [comment]
Nice!!! I just need this deb package :)

**Comment by kyrie-z** [comment]
Thank you for answering me @Kangie @Ev1lbl0w

**Comment by KienKse** [comment]
I unninstaled the komorebi but mine right click doesnt appear. what should I do?

**Comment by sxmeer-ahmed** [comment]
Go to that particular folder 
Open Terminal there
Type : sudo rm -r file_name
Hope it works :)
