### ISSUE TITLE
Still says I can't set video wallpapers despite gstreamer1.0-libav being installed

### ISSUE THREAD

**Issue by JVTEAM** [cheesecakeufo/komorebi#233]
I installed it and rebooted.  Still gives the same orange prompt.

**Comment by Ev1lbl0w** [comment]
The detection method is very barebones, so it can be a false alarm.

What is your distribution? What package did you install that provides that lib?

**Comment by JVTEAM** [comment]
It did end up letting me add one despite the warning.
