### ISSUE TITLE
My komorebi doesn't load the full screen.

### ISSUE THREAD

**Issue by SilentHarbor** [cheesecakeufo/komorebi#236]
Hi, I'm having the same problem. I'm using the most recent version of Elementary OS. resolution is 1366 x 768 (16:9). I only have one screen.
![Screenshot from 2020-08-30 13 37 37](https://user-images.githubusercontent.com/70485222/91666881-1aaa1600-eac6-11ea-8ad1-ec204677e775.png)

**Comment by Ev1lbl0w** [comment]
I've fixed this issue on our fork at https://github.com/Komorebi-Fork/komorebi/pull/36, please let me know if everything works fine now.

**Comment by Kangie** [comment]
If you didn't compile this from source to resolve the issue, we've put the fix into the 2.2.1 release and you can download a .deb package in the komorebi-fork/komorebi repo.
