### ISSUE TITLE
RPM file?

### ISSUE THREAD

**Issue by EliazBobadilla** [cheesecakeufo/komorebi#253]

**Comment by EliazBobadilla** [comment]
Alien not working with the .deb

**Comment by Ev1lbl0w** [comment]
There is a [RPM build](https://build.opensuse.org/package/show/home%3ANNowakowski/Komorebi-Fork) on our [fork](https://github.com/Komorebi-Fork/komorebi), courtesy of @NNowakowski :slightly_smiling_face:

**Comment by EliazBobadilla** [comment]
Thanks :3
