### ISSUE TITLE
Video Wallpaper Issue with Radeon Graphics Card 

### ISSUE THREAD

**Issue by MrRetr017** [cheesecakeufo/komorebi#254]
Hey Guys! So I've been working for awhile on solving this issue but I can't seem to figure it out. The process to creating a live video wallpaper was very easy so kudos to the team for this program I love it, however, when I try to use the video wallpaper I created I get strange blur or random colors splashing on the desktop and when i use a normal image wallpaper it works as intended. It works well with custom static wallpapers, it is the live ones that give me that strange color problems. 

Now for my specifications

I am running POP!_OS 20.10

My desktop environment is x11  not wayland.

I have an amd radeon 5700xt GPU not sure if that's a problem if so do advice :) 

POP_OS! has the radeon open source drivers already installed so I don't think it's a driver issue, or it might be who knows haha. 

all the latest updates have been installed and I am running on a 165hz curved monitor I also tried 60hz and the issue still persist!

I installed all of the necessary components needed for running live videos wallpapers on the Linux desktop.
I followed the instructions exactly how it was written on the Github. and even tried the Komorebi 2.2.1 as well as the latest version! well that's pretty much all I got! I attached some screenshots bellow so you can see the difference between a normal image and a video image! Please advice and thank  you in advance guys!

![Screenshot from 2021-01-11 15-50-07](https://user-images.githubusercontent.com/75863404/104242396-bb212700-5424-11eb-992f-57568fdcc5c9.png)
![Screenshot from 2021-01-11 15-50-51](https://user-images.githubusercontent.com/75863404/104242459-cf652400-5424-11eb-939f-ff3ba47d77d5.png)

**Comment by Ev1lbl0w** [comment]
Take a look at Komorebi-Fork#50; there is a workaround you can try for now, but if that doesn't work, you'll have to uninstall the VAAPI driver while this doesn't get fixed.

**Comment by MrRetr017** [comment]
> Take a look at Komorebi-Fork#50; there is a workaround you can try for now, but if that doesn't work, you'll have to uninstall the VAAPI driver while this doesn't get fixed.

Alright my dude I'll try this out when I get home from work! Thank you so much for taking the time to reply!
