### ISSUE TITLE
Uninstalling breaks desktop

### ISSUE THREAD

**Issue by JDOG787** [cheesecakeufo/komorebi#270]
Hello, so I tried installing this package because I was looking to try to make an animated wallpaper, but it wasn't what I was looking for so I uninstalled it. Doing this made the icons on my desktop disappear and right clicking doesn't show anything. I've tried looking for other threads with this problem, but couldn't find any fixes. Any ideas on how I could fix this? Also I'm a fairly new Linux user using Linux mint. 

Thanks!

**Comment by MrBear2018** [comment]
https://github.com/cheesecakeufo/komorebi/issues/138#issue-362263857
I use solution from this issue ,and I make it

but I lost all the config before I install this sorfware,such as dock .etc
But my desktop is ok now , I just need to set my desktop again

**Comment by JDOG787** [comment]
@MrBear2018 aight thanks, I'll have to give it a try!

**Comment by JDOG787** [comment]
It worked thanks!
