### ISSUE TITLE
--   No package 'clutter-gst-3.0' found

### ISSUE THREAD

**Issue by Dang-The-Vuong** [cheesecakeufo/komorebi#272]
anonymous@pop-os:~/komorebi/build$ cmake .. && sudo make install
-- Checking for modules 'gtk+-3.0;glib-2.0>=2.38;gee-0.8;webkit2gtk-4.0;clutter-gtk-1.0;clutter-1.0;clutter-gst-3.0'
--   No package 'clutter-gst-3.0' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  CMakeLists.txt:14 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/anonymous/komorebi/build/CMakeFiles/CMakeOutput.log".

**Comment by soprex** [comment]
I tried and got the same error. Komorebi does not work on the latest Ubuntu versions and not work on Debian 10. Don't waste your time.

**Comment by djukaPHP** [comment]
Komorebi does not work on the latest Ubuntu versions nor the Debian 10. Do not waste your time.
