### ISSUE TITLE
Komorebi Icons and Right Click bug

### ISSUE THREAD

**Issue by ssCarion** [cheesecakeufo/komorebi#283]
I don`t use Linux for a long time, for two days to be specific, and I wanted to customize my background to a live wallpaper. I did a little bit of research on YouTube and I found a guy that talked about this specific application. I followed his steps and eventually I did my wallpaper, but i was unsatisfied with the UI icons and I decided to not use Komorebi. After I exited the program my desktop icon and trash icon disappeared, which triggers me a little bit, but worse is that now when I right click on my screen nothing shows up. Can anyone explain to me what`s going on?

**Comment by pendragons-code** [comment]
https://github.com/cheesecakeufo/komorebi#after-uninstalling-my-desktop-isnt-working-right-blank-or-no-icons

**Comment by pendragons-code** [comment]
also which distro? if you are using ubuntu:

gsettings set org.gnome.shell.extensions.desktop-icons show-home true
gsettings set org.gnome.shell.extensions.desktop-icons show-trash true

**Comment by ssCarion** [comment]
im using Mint

**Comment by ssCarion** [comment]
Thank you sooooooooooo much kind sir. Have a good day :D
