### ISSUE TITLE
Cannot uninstall komorebi

### ISSUE THREAD

**Issue by ZhinRyu** [cheesecakeufo/komorebi#290]
zhinryu@MS-7B84-5a3713f7:~$ sudo apt remove komorebi
[sudo] password for zhinryu:         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package komorebi
zhinryu@MS-7B84-5a3713f7:~$ cd komorebi/build
bash: cd: komorebi/build: No such file or directory
zhinryu@MS-7B84-5a3713f7:~$ sudo make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
zhinryu@MS-7B84-5a3713f7:~$ sudo -i
root@MS-7B84-5a3713f7:~# sudo apt remove komorebi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package komorebi

**Comment by pendragons-code** [comment]
https://github.com/cheesecakeufo/komorebi#uninstall

**Comment by ZhinRyu** [comment]
Hi i already tried the following step for the uninstall and it doesn't work

zhinryu@MS-7B84-5a3713f7:~$ mkdir build && cd build
mkdir: cannot create directory ‘build’: File exists
zhinryu@MS-7B84-5a3713f7:~$ cd komorebi/build
bash: cd: komorebi/build: No such file or directory
zhinryu@MS-7B84-5a3713f7:~$ cd komorebi/build
bash: cd: komorebi/build: No such file or directory
zhinryu@MS-7B84-5a3713f7:~$ sudo make uninstall
[sudo] password for zhinryu:         
make: *** No rule to make target 'uninstall'.  Stop.

**Comment by ZhinRyu** [comment]
btw me running on Ubuntu 20.04 on Elementary OS

**Comment by DrBrad** [comment]
Same issue here, however I also cant run it...
