### ISSUE TITLE
Live Wallpaper shows black screen

### ISSUE THREAD

**Issue by BIGBEASTISHANK** [cheesecakeufo/komorebi#323]
![image](https://user-images.githubusercontent.com/77890275/162503990-f0ec4f86-d338-4f11-af4f-e5cad86b6aed.png)

video just shows black wallpaper and no video works

**Comment by evo0616lution** [comment]
Same thing here! I am running it on Pop OS 21.10

**Comment by proleriana** [comment]
Same stuff, I am on Ubuntu 22.10. Guess it got broken after some minor updates

**Comment by Jervx** [comment]
I have solve this before in ubuntu 21.10, now I forgot how to solve it again. But I remember it's about a certain dependencies for playing video, I really forgot fuck.

It's kinda like this 

sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

**Comment by proleriana** [comment]
> I have solve this before in ubuntu 21.10, now I forgot how to solve it again. But I remember it's about a certain dependencies for playing video, I really forgot fuck.
> 
> 
> 
> It's kinda like this 
> 
> 
> 
> sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

That's too bad, but it didn't fix my an issue for me on Pop! Os 22.04 (all of the stuff came as already installed). :(
If you by any chance find a solution please share

**Comment by Jervx** [comment]
Hey I reinstalled ubuntu 21.10, I finally got the video working. Idk how I did it but I'm trying to treceback what dependencies I installed. I will reinstall ubuntu 21.10 again and find the exact dependency that made it work. I'll be back & hope it will work on your OS too..

**Comment by Jervx** [comment]
> Hey I reinstalled ubuntu 21.10, I finally got the video working. Idk how I did it but I'm trying to treceback what dependencies I installed. I will reinstall ubuntu 21.10 again and find the exact dependency that made it work. I'll be back & hope it will work on your OS too..
> 

Apparently I tried it again and got stucked again for 2 hours. Though I got it working but I couldn't exactly locate what I did so I'm reformatting and reinstalling it again for 3rd time. If I couldn't I will send here my entire bash history.

**Comment by Jervx** [comment]
Finally after 3rd attempt It finally worked. 

I Apologize in advance because my English gramar is so bad.

If you want a proof that it works in Ubuntu 21.10 [Watch my video here](https://youtu.be/vkCM1W-FKzo).

### System information
```sh
OS: Ubuntu 21.10 x86_64 
Packages: 2249 (dpkg), 13 (snap) 
Shell: zsh 5.8 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
CPU: Intel i5-7200U (4) @ 3.100GHz 
GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520  
GPU: Intel HD Graphics 620 
```

### Komorebi Version _**komorebi-2.1-64-bit.deb**_

<hr>

This solution is not yes summarized & I'm not sure if this is applicable for other distro. Please if you know about these packages let me know what commands to remove so that it will become shorter & accurate.

<hr>

### Batch 1 
```bash
sudo apt-get install g++
sudo apt-get install gir1.2-gtkclutter-1.0
sudo apt-get install autoconf automake autopoint appstream build-essential cmake git libass-dev libbz2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libnuma-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libturbojpeg0-dev libvorbis-dev libx264-dev libxml2-dev libvpx-dev m4 make meson nasm ninja-build patch pkg-config python tar zlib1g-dev

sudo apt-get install libva-dev libdrm-dev
sudo apt-get install libgtop2-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install gtk+-3.0
sudo apt-get install libgtop-2.0
sudo apt-get install glib-2.0
sudo apt-get install gee-0.8
sudo apt install libwnck-3.0

sudo apt-get install gtk3.0 gee-0.8 webkit2gtk-4.0 clutter-gtk-1.0 clutter-1.0 clutter-gst-3.0
sudo apt-get install gstreamer1.0-libav intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev libnotify-dev libwebkit2gtk-4.0-dev
```
<hr>

At this point I've downloaded the packages bellow because I can't install them using apt from previous commands, if you encounter some of this, just find them in google and install them.

I downloaded them from [https://debian.pkgs.org/](https://debian.pkgs.org/).

_Note : If you are using other distro so try finding the packages that is compatible for your distro_

After downloading the packages that is not installed from previous command. I installed them using dpkg

### Batch 2 
```sh
sudo dpkg -i libwnck-3-0_40.0-1_amd64.deb
sudo dpkg -i libglib2.0-doc_2.58.3-2+deb10u3_all.deb
sudo dpkg -i gstreamer1.0-doc_1.14.4-1_all.deb
sudo apt install libpulse-dev
sudo apt install libgstrtspserver-1.0-dev gstreamer1 0-rtsp
sudo apt install libpulse-mainloop-glib0
sudo apt install build-essential 
sudo apt install appstream-util
sudo apt install libnm-dev
sudo apt install gstreamer-video-1.0
```

I run Komorebi again

```sh
/System/Applications/komorebi 
```

but still not working

### Batch 3 
```sh
sudo apt-get install libgstreamer*
sudo apt install -y libgstreamer-plugins-base1.0-dev
sudo apt autoremove
```

_Note: At this point, if **sudo apt-get install libgstreamer** dosn't work, just proceed_


I executed autoremove because apt says:

```sh
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
Use 'sudo apt autoremove' to remove them.
```


I tried to run komorebi again 

```sh
/System/Applications/komorebi
```

Finally it worked. 



I think this **"chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1"** causes Komorebi to not function well (I'm not sure about this)

**Comment by Jervx** [comment]
> Same stuff, I am on Ubuntu 22.10. Guess it got broken after some minor updates

I'll be trying my solution above next month if it will work on Ubuntu 22.04. Currently, I can't use 22.04 yet because some dependencies/packages/apps are not yet available for 22.04 I'll wait for some time

**Comment by proleriana** [comment]
> Finally after 3rd attempt It finally worked. 
> 
> 
> 
> I Apologize in advance because my English gramar is so bad.
> 
> 
> 
> If you want a proof that it works in Ubuntu 21.10 [Watch my video here](https://youtu.be/vkCM1W-FKzo).
> 
> 
> 
> ### System information
> 
> ```sh
> 
> OS: Ubuntu 21.10 x86_64 
> 
> Packages: 2249 (dpkg), 13 (snap) 
> 
> Shell: zsh 5.8 
> 
> DE: GNOME 40.5 
> 
> WM: Mutter 
> 
> WM Theme: Adwaita 
> 
> Theme: Yaru-dark [GTK2/3] 
> 
> Icons: Yaru [GTK2/3] 
> 
> CPU: Intel i5-7200U (4) @ 3.100GHz 
> 
> GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520  
> 
> GPU: Intel HD Graphics 620 
> 
> ```
> 
> 
> 
> ### Komorebi Version _**komorebi-2.1-64-bit.deb**_
> 
> 
> 
> <hr>
> 
> 
> 
> This solution is not yes summarized & I'm not sure if this is applicable for other distro. Please if you know about these packages let me know what commands to remove so that it will become shorter & accurate.
> 
> 
> 
> <hr>
> 
> 
> 
> ### Batch 1 
> 
> ```bash
> 
> sudo apt-get install g++
> 
> sudo apt-get install gir1.2-gtkclutter-1.0
> 
> sudo apt-get install autoconf automake autopoint appstream build-essential cmake git libass-dev libbz2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libnuma-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libturbojpeg0-dev libvorbis-dev libx264-dev libxml2-dev libvpx-dev m4 make meson nasm ninja-build patch pkg-config python tar zlib1g-dev
> 
> 
> 
> sudo apt-get install libva-dev libdrm-dev
> 
> sudo apt-get install libgtop2-dev
> 
> sudo apt-get install libgtk-3-dev
> 
> sudo apt-get install gtk+-3.0
> 
> sudo apt-get install libgtop-2.0
> 
> sudo apt-get install glib-2.0
> 
> sudo apt-get install gee-0.8
> 
> sudo apt install libwnck-3.0
> 
> 
> 
> sudo apt-get install gtk3.0 gee-0.8 webkit2gtk-4.0 clutter-gtk-1.0 clutter-1.0 clutter-gst-3.0
> 
> sudo apt-get install gstreamer1.0-libav intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev libnotify-dev libwebkit2gtk-4.0-dev
> 
> ```
> 
> <hr>
> 
> 
> 
> At this point I've downloaded the packages bellow because I can't install them using apt from previous commands, if you encounter some of this, just find them in google and install them.
> 
> 
> 
> I downloaded them from [https://debian.pkgs.org/](https://debian.pkgs.org/).
> 
> 
> 
> _Note : If you are using other distro so try finding the packages that is compatible for your distro_
> 
> 
> 
> After downloading the packages that is not installed from previous command. I installed them using dpkg
> 
> 
> 
> ### Batch 2 
> 
> ```sh
> 
> sudo dpkg -i libwnck-3-0_40.0-1_amd64.deb
> 
> sudo dpkg -i libglib2.0-doc_2.58.3-2+deb10u3_all.deb
> 
> sudo dpkg -i gstreamer1.0-doc_1.14.4-1_all.deb
> 
> sudo apt install libpulse-dev
> 
> sudo apt install libgstrtspserver-1.0-dev gstreamer1 0-rtsp
> 
> sudo apt install libpulse-mainloop-glib0
> 
> sudo apt install build-essential 
> 
> sudo apt install appstream-util
> 
> sudo apt install libnm-dev
> 
> sudo apt install gstreamer-video-1.0
> 
> ```
> 
> 
> 
> I run Komorebi again
> 
> 
> 
> ```sh
> 
> /System/Applications/komorebi 
> 
> ```
> 
> 
> 
> but still not working
> 
> 
> 
> ### Batch 3 
> 
> ```sh
> 
> sudo apt-get install libgstreamer*
> 
> sudo apt install -y libgstreamer-plugins-base1.0-dev
> 
> sudo apt autoremove
> 
> ```
> 
> 
> 
> _Note: At this point, if **sudo apt-get install libgstreamer** dosn't work, just proceed_
> 
> 
> 
> 
> 
> I executed autoremove because apt says:
> 
> 
> 
> ```sh
> 
> The following packages were automatically installed and are no longer required:
> 
>   chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
> 
> Use 'sudo apt autoremove' to remove them.
> 
> ```
> 
> 
> 
> 
> 
> I tried to run komorebi again 
> 
> 
> 
> ```sh
> 
> /System/Applications/komorebi
> 
> ```
> 
> 
> 
> Finally it worked. 
> 
> 
> 
> 
> 
> 
> 
> I think this **"chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1"** causes Komorebi to not function well (I'm not sure about this)

Sadly, even after all those installations, still no luck in enabling video wallpapers. I guess some extra steps are required for a Ubuntu 22.04 installation. Still, thank you for this research, I am sure that it would be helpful to people who use Ubuntu 21.10

**Comment by proleriana** [comment]
I guess if I am really keen about live wallpapers the best way around is to install Ubuntu 21.10 and follow your guide xd

**Comment by Jervx** [comment]
> > Finally after 3rd attempt It finally worked. 
> > 
> > 
> > 
> > I Apologize in advance because my English gramar is so bad.
> > 
> > 
> > 
> > If you want a proof that it works in Ubuntu 21.10 [Watch my video here](https://youtu.be/vkCM1W-FKzo).
> > 
> > 
> > 
> > ### System information
> > 
> > ```sh
> > 
> > OS: Ubuntu 21.10 x86_64 
> > 
> > Packages: 2249 (dpkg), 13 (snap) 
> > 
> > Shell: zsh 5.8 
> > 
> > DE: GNOME 40.5 
> > 
> > WM: Mutter 
> > 
> > WM Theme: Adwaita 
> > 
> > Theme: Yaru-dark [GTK2/3] 
> > 
> > Icons: Yaru [GTK2/3] 
> > 
> > CPU: Intel i5-7200U (4) @ 3.100GHz 
> > 
> > GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520  
> > 
> > GPU: Intel HD Graphics 620 
> > 
> > ```
> > 
> > 
> > 
> > ### Komorebi Version _**komorebi-2.1-64-bit.deb**_
> > 
> > 
> > 
> > <hr>
> > 
> > 
> > 
> > This solution is not yes summarized & I'm not sure if this is applicable for other distro. Please if you know about these packages let me know what commands to remove so that it will become shorter & accurate.
> > 
> > 
> > 
> > <hr>
> > 
> > 
> > 
> > ### Batch 1 
> > 
> > ```bash
> > 
> > sudo apt-get install g++
> > 
> > sudo apt-get install gir1.2-gtkclutter-1.0
> > 
> > sudo apt-get install autoconf automake autopoint appstream build-essential cmake git libass-dev libbz2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libnuma-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libturbojpeg0-dev libvorbis-dev libx264-dev libxml2-dev libvpx-dev m4 make meson nasm ninja-build patch pkg-config python tar zlib1g-dev
> > 
> > 
> > 
> > sudo apt-get install libva-dev libdrm-dev
> > 
> > sudo apt-get install libgtop2-dev
> > 
> > sudo apt-get install libgtk-3-dev
> > 
> > sudo apt-get install gtk+-3.0
> > 
> > sudo apt-get install libgtop-2.0
> > 
> > sudo apt-get install glib-2.0
> > 
> > sudo apt-get install gee-0.8
> > 
> > sudo apt install libwnck-3.0
> > 
> > 
> > 
> > sudo apt-get install gtk3.0 gee-0.8 webkit2gtk-4.0 clutter-gtk-1.0 clutter-1.0 clutter-gst-3.0
> > 
> > sudo apt-get install gstreamer1.0-libav intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev libnotify-dev libwebkit2gtk-4.0-dev
> > 
> > ```
> > 
> > <hr>
> > 
> > 
> > 
> > At this point I've downloaded the packages bellow because I can't install them using apt from previous commands, if you encounter some of this, just find them in google and install them.
> > 
> > 
> > 
> > I downloaded them from [https://debian.pkgs.org/](https://debian.pkgs.org/).
> > 
> > 
> > 
> > _Note : If you are using other distro so try finding the packages that is compatible for your distro_
> > 
> > 
> > 
> > After downloading the packages that is not installed from previous command. I installed them using dpkg
> > 
> > 
> > 
> > ### Batch 2 
> > 
> > ```sh
> > 
> > sudo dpkg -i libwnck-3-0_40.0-1_amd64.deb
> > 
> > sudo dpkg -i libglib2.0-doc_2.58.3-2+deb10u3_all.deb
> > 
> > sudo dpkg -i gstreamer1.0-doc_1.14.4-1_all.deb
> > 
> > sudo apt install libpulse-dev
> > 
> > sudo apt install libgstrtspserver-1.0-dev gstreamer1 0-rtsp
> > 
> > sudo apt install libpulse-mainloop-glib0
> > 
> > sudo apt install build-essential 
> > 
> > sudo apt install appstream-util
> > 
> > sudo apt install libnm-dev
> > 
> > sudo apt install gstreamer-video-1.0
> > 
> > ```
> > 
> > 
> > 
> > I run Komorebi again
> > 
> > 
> > 
> > ```sh
> > 
> > /System/Applications/komorebi 
> > 
> > ```
> > 
> > 
> > 
> > but still not working
> > 
> > 
> > 
> > ### Batch 3 
> > 
> > ```sh
> > 
> > sudo apt-get install libgstreamer*
> > 
> > sudo apt install -y libgstreamer-plugins-base1.0-dev
> > 
> > sudo apt autoremove
> > 
> > ```
> > 
> > 
> > 
> > _Note: At this point, if **sudo apt-get install libgstreamer** dosn't work, just proceed_
> > 
> > 
> > 
> > 
> > 
> > I executed autoremove because apt says:
> > 
> > 
> > 
> > ```sh
> > 
> > The following packages were automatically installed and are no longer required:
> > 
> >   chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
> > 
> > Use 'sudo apt autoremove' to remove them.
> > 
> > ```
> > 
> > 
> > 
> > 
> > 
> > I tried to run komorebi again 
> > 
> > 
> > 
> > ```sh
> > 
> > /System/Applications/komorebi
> > 
> > ```
> > 
> > 
> > 
> > Finally it worked. 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > I think this **"chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1"** causes Komorebi to not function well (I'm not sure about this)
> 
> Sadly, even after all those installations, still no luck in enabling video wallpapers. I guess some extra steps are required for a Ubuntu 22.04 installation. Still, thank you for this research, I am sure that it would be helpful to people who use Ubuntu 21.10

Oh I see..., I'll be switching to ubuntu 22.04 next month, If I found a fix, I'll share it here. If I didn't I will finally forget about komorebi 😔 & forget about aesthetic setup. but I hope the original developers will make an update about these issues.

**Comment by proleriana** [comment]
> extra

thank you kindly, I will patiently wait for an 22.04 fix from you :)

**Comment by proleriana** [comment]
I've tested it out on a kubuntu 21.10 machine, and my live wallpapers worked as a charm. I really suppose it has to do with some minor 22.04 updates

**Comment by Jervx** [comment]
> ```shell
> sudo apt-get install libgstreamer*
> 
> sudo apt install -y libgstreamer-plugins-base1.0-dev
> 
> sudo apt autoremove
> ```

I switched to Ubuntu 22.04 and It worked using the batch of commands I posted before but I execute them in this order

Batch 3 
Batch 2
Batch 1 
Batch 2
Batch 3

Then I ran komorebi and it worked again
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif)

**Comment by Jervx** [comment]
> Thank you kindly, I will patiently wait for an 22.04 fix from you :)


I switched to Ubuntu 22.04 and It worked using the batch of commands I posted before but I execute them in this order

Batch 3 
Batch 2
Batch 1 
Batch 2
Batch 3

Then I ran komorebi and it worked again
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif)

**Comment by strusty** [comment]
At this stage, I have tried both lists of dependency installs.  Still no video.  I do note that something has changed, as gstreamer-video-1.0 is not installable, its like it never existed.  Also there is a repeated typo missing the dot on this line:
gstreamer1 0-rtsp ...
gstreamer1.0-rtsp

**Comment by Jervx** [comment]
> At this stage, I have tried both lists of dependency installs.  Still no video.  I do note that something has changed, as gstreamer-video-1.0 is not installable, its like it never existed.  Also there is a repeated typo missing the dot on this line:
> gstreamer1 0-rtsp ...
> gstreamer1.0-rtsp

thanks for noticing the typo ✨

**Comment by pendragons-code** [comment]
Assuming that this was made before ubuntu used wayland by default, I'm  guessing X should still let it run fine

**Comment by strusty** [comment]
The current problem for me is using Xorg, not Wayland.  The difference between this 22.04 and the other two that are working (only video playback is problem), is that there is no provision for installing gstreamer-video-1.0.  It appears to point instead to libgstreamer-plugins-base1.0-dev and valac, but even when installed the problem remains. Package gstreamer1.0 is available and installed, but no help.

**Comment by DeMineArchiver** [comment]
> > Thank you kindly, I will patiently wait for an 22.04 fix from you :)
> 
> I switched to Ubuntu 22.04 and It worked using the batch of commands I posted before but I execute only this commands
> 
> sudo apt-get install libgstreamer* sudo apt install -y libgstreamer-plugins-base1.0-dev sudo apt autoremove sudo apt install libpulse-dev sudo apt install libgstrtspserver-1.0-dev gstreamer1.0-rtsp sudo apt install libpulse-mainloop-glib0 sudo apt install build-essential sudo apt install appstream-util sudo apt install libnm-dev sudo apt install gstreamer-video-1.0 sudo apt-get install gir1.2-gtkclutter-1.0 sudo apt-get install libva-dev libdrm-dev sudo apt-get install libgtop2-dev sudo apt-get install libgtk-3-dev sudo apt-get install libva-dev libdrm-dev sudo apt-get install libgtop2-dev sudo apt-get install glib-2.0 sudo apt-get install gee-0.8 sudo apt install libwnck-3.0 sudo apt-get install gstreamer1.0-libav intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev libnotify-dev libwebkit2gtk-4.0-dev
> 
> Then I ran komorebi and it worked again ![ezgif com-gif-maker](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif) [ ![ezgif com-gif-maker](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif) ](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif) [ ](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif)

There is an error for me when installing the packages: 
```
The following packages have unmet dependencies:

 libegl-mesa0 : Depends: libgbm1 (= 22.0.1-1ubuntu2) but 22.0.1-1ubuntu2.1 is to be installed

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by Jervx** [comment]
> > Thank you kindly, I will patiently wait for an 22.04 fix from you :)
> 
> I switched to Ubuntu 22.04 and It worked using the batch of commands I posted before but I execute only this commands
> 
> sudo apt-get install libgstreamer* sudo apt install -y libgstreamer-plugins-base1.0-dev sudo apt autoremove sudo apt install libpulse-dev sudo apt install libgstrtspserver-1.0-dev gstreamer1.0-rtsp sudo apt install libpulse-mainloop-glib0 sudo apt install build-essential sudo apt install appstream-util sudo apt install libnm-dev sudo apt install gstreamer-video-1.0 sudo apt-get install gir1.2-gtkclutter-1.0 sudo apt-get install libva-dev libdrm-dev sudo apt-get install libgtop2-dev sudo apt-get install libgtk-3-dev sudo apt-get install libva-dev libdrm-dev sudo apt-get install libgtop2-dev sudo apt-get install glib-2.0 sudo apt-get install gee-0.8 sudo apt install libwnck-3.0 sudo apt-get install gstreamer1.0-libav intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev libnotify-dev libwebkit2gtk-4.0-dev
> 
> Then I ran komorebi and it worked again ![ezgif com-gif-maker](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif) [ ![ezgif com-gif-maker](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif) ](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif) [ ](https://user-images.githubusercontent.com/48374007/174472782-63159ea9-9685-4b66-866a-696a30a00e0b.gif)

UPDATE : 

on Ubuntu 23.04 I only tried using this command to make it work. You can also try it on previous Ubuntu release
```
sudo apt install gstreamer1.0-libav
```

**Comment by Jervx** [comment]
> Welcome to Komorebi ../src/intel/isl/isl.c:2216: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available. Reading config file.. [INFO]: loading Gst libva info: VA-API version 1.14.0 libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so libva info: Found init function __vaDriverInit_1_14 libva info: va_openDriver() returns 0
> 
> I got this and still video wallpaper blank

UPDATE July 21 2023: 

I finally installed Ubuntu 23.04, And we only need this command to make it work. You can also try it on previous Ubuntu release

sudo apt install gstreamer1.0-libav

**Comment by BIGBEASTISHANK** [comment]
I guess i should close this now, everyone has fixed their issue, and i dont use komorebi now, i may use it in feature Bye :wave:
