### ISSUE TITLE
No Fedora Support

### ISSUE THREAD

**Issue by HoferSimon** [cheesecakeufo/komorebi#325]
Hey,

I should like to get komorebi on my Fedora 36, but unfortunately there is no Fedora support. There is only the possibility to install it for Debian Based Distros.... Is there any way to install it on Fedora?
![gnome-shell-screenshot-8q7t9h](https://user-images.githubusercontent.com/73385668/174492446-b8fa935c-1143-45ae-bdbc-3f6498463ece.png)

**Comment by randellb** [comment]
https://fedora.pkgs.org/35/rpm-sphere-x86_64/komorebi-2.1-1.x86_64.rpm.html

**Comment by randellb** [comment]
https://fedora.pkgs.org/35/rpm-sphere-x86_64/komorebi-2.1-1.x86_64.rpm.html
![Screenshot from 2022-06-21 23-10-43](https://user-images.githubusercontent.com/107773858/174936222-f454b0a5-9d4b-4a03-8524-57c32c3cd62c.png)

VT323 Fonts required
https://fonts.google.com/specimen/VT323
![Screenshot from 2022-06-21 23-15-45](https://user-images.githubusercontent.com/107773858/174936309-f07bce97-57a0-4db7-a4f1-6893bfaf5662.png)

Open the ttf file and click on install and it should work fine

**Comment by HoferSimon** [comment]
Thank you :)

**Comment by NyllRE** [comment]
I have tried to install everything even the fonts but it still couldn't work because it couldn't recognize the font installation and still tells me that it can't be installed. why isn't it detecting the fonts?

**Comment by 3laws** [comment]
@cheesecakeufo Can we have VT323 not be a hard dependency?
