### ISSUE TITLE
Can't uninstall it

### ISSUE THREAD

**Issue by rodukov** [cheesecakeufo/komorebi#334]
> Can't uninstall it
```
~/komorebi/build$  sudo make uninstall
```
make: *** No rule to make target 'uninstall'.  Stop.
How to remove it?

**Comment by klanjabrik** [comment]
Hi @rodukov . You can use checkinstall command.

Execute the following commands in the source package directory (eg. ~/komorebi/build):
1. sudo apt-get install checkinstall
2. sudo checkinstall
3. sudo apt remove build
