### ISSUE TITLE
Ubuntu 22.04, tried to manually install, it didn't work

### ISSUE THREAD

**Issue by shawazi** [cheesecakeufo/komorebi#348]
Now there's a Komorebi icon in my applications list, but clicking it does nothing. I deleted the komorebi folder. I also installed the .deb package. it installed, but clicking the komorebi icon does nothing. Can anyone suggest what to do here? Thank you

**Comment by shawazi** [comment]
i restored the folder, but now "sudo make uninstall" results in this:

**Comment by shawazi** [comment]
shawaz@shawaz-laptop:~/komorebi$ sudo make uninstall
[sudo] password for shawaz: 
make: *** No rule to make target 'uninstall'.  Stop.
shawaz@shawaz-laptop:~/komorebi$

**Comment by Shahriar-Shakil** [comment]
same here. I tried both ways but it's not working. by the way, wallpaper creator has been lunched

**Comment by shawazi** [comment]
yo Shahriar, komorebi randomly started working for me a couple days ago after restarting my laptop. i'm not sure if my system was updated recently. 

I don't know how it was fixed, but i deleted it following komorebi's directions on some of their other issues. you can google "komorebi uninstall from ubuntu" and click some of the github issues links to see the solution. there are a few different options for solving it.
