### ISSUE TITLE
Custom wallpapers not showing.

### ISSUE THREAD

**Issue by dowttie** [cheesecakeufo/komorebi#55]
I tried to make a few custom wallpapers with the wallpaper creator and I moved them to /System/Resources/Komorebi/ but they don't show up in komorebi.

**Comment by tgm4883** [comment]
I had this problem too. You need to have a wallpaper.jpg file included with your bundle. I just copied it from the one of the preexisting wallpapers.

**Comment by kuboosoft** [comment]
without a log the developer cannot help us, my friends...

**Comment by addoull** [comment]
Just rename thumb.jpg to wallpaper.jpg in each custom wallpaper folder

**Comment by aiamuzz** [comment]
Hi,

I just created a video wallpaper ... same isn't showing in the list ... i can see that we can manually put it into the `system/resources` folder.

But i am not able to locate the path where the created wallpapers are stored ... any idea where does the 'Wallpaper Creator' application store created wallpapers ?

**Comment by aiamuzz** [comment]
ok found it ... it had created it in the home folder with the wallpaper name.

**Comment by andyliuhaowen** [comment]
@aiamuzz Could you please close this issue if your problem is resolved?
