### ISSUE TITLE
Sound from custom wallpaper video

### ISSUE THREAD

**Issue by rodrigondec** [cheesecakeufo/komorebi#86]
There is no config or launch option to mute a custom wallpaper video. All my custom wallpapers video types have sound on the video. 
But I don't want to have the sound active all the time. Could be made a option just like --disable-video for the sound?

**Comment by kevinnegy** [comment]
I'm on Ubuntu 20.04, in the Ubuntu sound settings, I'm able to turn down or mute the Komorebi sound.
